spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pagamento?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
